version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/app
    ports:
      - "8080:8080"
  db:
    image: python:3.9
    command: sh -c "apt-get update && apt-get install -y sqlite3 && python -c 'import sqlite3'"
    volumes:
      - db-data:/db

volumes:
  db-data:

