global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'django'
    scrape_interval: 5s
    static_configs:
      - targets: ['django:8000']

  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['prometheus:9090']
